name: Build and Package Flet Application (macOS)

on:
  workflow_dispatch:  # Ручной запуск

jobs:
  build:
    runs-on: macos-latest  # macOS для сборки .app

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller flet

    - name: Build macOS .app
      run: |
        pyinstaller --onefile --windowed --name "KIVI Retail DEV" src/main.py

    - name: Upload .app
      uses: actions/upload-artifact@v4
      with:
        name: MyFletApp-macOS
        path: dist/MyFletApp.app